language: ruby
rvm:
  - 2.2
install: gem install ruby_dep -v 1.3.1 && gem install listen -v 3.0.8 && gem install jekyll -v 2.4.0
script: jekyll build
after_success: bash postdeploy.sh
notifications:
    slack: aiacc:DQJx1jxSipYMHzXBVtf4kMGH