language: ruby
rvm:
  - 2.2
install: gem install jekyll && gem install jekyll-redirect-from && gem install s3_website
script: jekyll build
after_success: s3_website push
notifications:
    slack: aiacc:DQJx1jxSipYMHzXBVtf4kMGH